### ISSUE TITLE
pathToSVG is broken

### ISSUE THREAD

**Issue by michaelnimbs** [fredli74/Typr.ts#1]
pathToSVG is broken, because the font instance is used as first parameter, but only the path is used in Typr.js.

`return Typr_js_1.Typr.U.pathToSVG(this, path);`

but in the source it is:

`Typr.U.pathToSVG = function (path, prec) {}`

So I guess it should be

`return Typr_js_1.Typr.U.pathToSVG(path);`

Same with `pathToContext`, otherwise thank you for the library.

**Comment by fredli74** [comment]
Thank you, good catch. I am using my own TyprPathToSVGPath function that optimizes paths down to the smallest possible representation by combining and replacing instructions. That's why I have never tested the built-in pathToSVG function.

fixed in 26e1bcaa99bd28110beb5ee43a17532f07448284

**Comment by michaelnimbs** [comment]
Thank you for the quick release!
