### ISSUE TITLE
Function getPairAdjustment returns double the amount of kerning offset

### ISSUE THREAD

**Issue by TimmyTommy** [fredli74/Typr.ts#3]
Hello,

I found a bug with the kerning of texts.

Typr.U.getPairAdjustment returns the double amount of kerning offset.

I already submitted an issue in the troika-three-text repository of [lojjic](https://github.com/lojjic) because he uses your library.
https://github.com/protectwise/troika/issues/196

Here is a screenshot of before and after I divide the value returned by getPairAdjustment by 2. The top one is wrong. 
The 'T' and the 'e' should not be that close to each other.
The font I used is Calibri.

![image](https://user-images.githubusercontent.com/11164463/157755520-effd927d-82b0-47f5-be27-4b6814f43675.png)

I found out, it could be this change which caused the bug: https://github.com/fredli74/Typr.ts/commit/a9f3fe3a2e55c01aeae28ac0ef1ac3e848478b7f

It seems like getPairAdjustment should only use either the 'GPOS' data or the 'kern' data and not both at the same time, because while debugging I saw, that they both return the same amount of kerning. So down below in `if(font.kern)` the offset is applied a second time.

**Comment by fredli74** [comment]
Ah, classic, fix one bug, introduce a new one. 😁

As far as I've seen, the GPOS should have priority over kern. I'll fix it, let me just do some more research.

**Comment by fredli74** [comment]
Could you please rebuild using `@fredli74/typr@0.3.5` and see if that solves your issue?

**Comment by lojjic** [comment]
That seems to have fixed it, thank you @fredli74!

![image](https://user-images.githubusercontent.com/138124/157967522-183cfd19-2415-4262-bbc9-681691622299.png)

@TimmyTommy I'll publish a troika-three-text release using the updated Typr soon.

**Comment by fredli74** [comment]
Perfect! Thanks for finding this @TimmyTommy

**Comment by TimmyTommy** [comment]
Looks good! Thank you for fixing it so fast.

![image](https://user-images.githubusercontent.com/11164463/158024751-185f90b6-3099-4746-a367-c6d2d812f93c.png)
